/**
 * Research Center: evidence lookup + exercise suggestion.
 *
 * Papers come from Semantic Scholar (no key required), with PubMed E-utilities
 * as a fallback. Exercise suggestions come from Claude when ANTHROPIC_API_KEY is
 * configured, and from a built-in protocol library otherwise — so the feature
 * works out of the box with no external accounts.
 */

import Anthropic from '@anthropic-ai/sdk';

export interface Paper {
    title: string;
    year: number | null;
    authors: string;
    venue: string;
    abstract: string;
    url: string;
    source: 'semantic_scholar' | 'pubmed';
}

export interface SuggestedExercise {
    name: string;
    nameAr: string;
    sets: string;
    reps: string;
    duration: string;
    instructions: string;
    rationale: string;
    /** 'ai' when generated by Claude, 'library' when taken from the built-in protocols. */
    origin: 'ai' | 'library';
}

const UA = 'KartosPhysio/1.0 (clinic management system)';

export async function findPapers(diagnosis: string, limit = 6): Promise<Paper[]> {
    const query = `${diagnosis} physiotherapy rehabilitation exercise`;
    const fromScholar = await semanticScholar(query, limit);
    if (fromScholar.length) return fromScholar;
    return pubmed(query, limit);
}

async function semanticScholar(query: string, limit: number): Promise<Paper[]> {
    const url = new URL('https://api.semanticscholar.org/graph/v1/paper/search');
    url.searchParams.set('query', query);
    url.searchParams.set('limit', String(limit));
    url.searchParams.set('fields', 'title,year,authors,venue,abstract,url,externalIds');

    try {
        const res = await fetch(url, { headers: { 'user-agent': UA } });
        if (!res.ok) return [];
        const body = (await res.json()) as { data?: any[] };
        return (body.data ?? []).map((p) => ({
            title: p.title ?? 'Untitled',
            year: p.year ?? null,
            authors: (p.authors ?? [])
                .slice(0, 4)
                .map((a: any) => a.name)
                .join(', '),
            venue: p.venue ?? '',
            abstract: p.abstract ?? '',
            url: p.url ?? (p.externalIds?.DOI ? `https://doi.org/${p.externalIds.DOI}` : ''),
            source: 'semantic_scholar' as const
        }));
    } catch {
        return [];
    }
}

async function pubmed(query: string, limit: number): Promise<Paper[]> {
    const base = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils';
    try {
        const search = new URL(`${base}/esearch.fcgi`);
        search.searchParams.set('db', 'pubmed');
        search.searchParams.set('term', query);
        search.searchParams.set('retmax', String(limit));
        search.searchParams.set('retmode', 'json');

        const ids = (await (await fetch(search, { headers: { 'user-agent': UA } })).json()) as any;
        const idList: string[] = ids?.esearchresult?.idlist ?? [];
        if (!idList.length) return [];

        const summary = new URL(`${base}/esummary.fcgi`);
        summary.searchParams.set('db', 'pubmed');
        summary.searchParams.set('id', idList.join(','));
        summary.searchParams.set('retmode', 'json');

        const detail = (await (await fetch(summary, { headers: { 'user-agent': UA } })).json()) as any;
        return idList.map((id) => {
            const rec = detail?.result?.[id] ?? {};
            return {
                title: rec.title ?? 'Untitled',
                year: rec.pubdate ? Number(String(rec.pubdate).slice(0, 4)) || null : null,
                authors: (rec.authors ?? [])
                    .slice(0, 4)
                    .map((a: any) => a.name)
                    .join(', '),
                venue: rec.fulljournalname ?? rec.source ?? '',
                abstract: '',
                url: `https://pubmed.ncbi.nlm.nih.gov/${id}/`,
                source: 'pubmed' as const
            };
        });
    } catch {
        return [];
    }
}

/** Diagnosis keyword → protocol. Used directly when no API key is configured. */
const PROTOCOLS: { match: RegExp; exercises: Omit<SuggestedExercise, 'origin'>[] }[] = [
    {
        match: /\b(lbp|low back|lumbar|back pain|discogenic|ظهر)\b/i,
        exercises: [
            {
                name: 'Pelvic Tilt',
                nameAr: 'إمالة الحوض',
                sets: '3 sets',
                reps: '10 reps',
                duration: 'Hold 10s',
                instructions: 'Lying supine with knees bent, flatten the lumbar spine against the floor by tilting the pelvis, then release.',
                rationale: 'Motor control retraining of the lumbopelvic region; first-line for non-specific low back pain.'
            },
            {
                name: 'Knee to Chest Stretch',
                nameAr: 'شد الركبة إلى الصدر',
                sets: '3 sets',
                reps: '5 reps each side',
                duration: 'Hold 30s',
                instructions: 'Supine, draw one knee toward the chest until a gentle stretch is felt in the lower back. Keep the other leg relaxed.',
                rationale: 'Reduces paraspinal tone and improves lumbar flexion tolerance.'
            },
            {
                name: 'Cat-Cow Stretch',
                nameAr: 'تمرين القطة والبقرة',
                sets: '2 sets',
                reps: '10 reps',
                duration: 'Slow tempo',
                instructions: 'On hands and knees, alternate between spinal flexion and extension in a slow, controlled rhythm.',
                rationale: 'Restores segmental mobility and reduces pain-related movement guarding.'
            },
            {
                name: 'Bird Dog',
                nameAr: 'تمرين الطائر والكلب',
                sets: '3 sets',
                reps: '8 reps each side',
                duration: 'Hold 5s',
                instructions: 'From four-point kneeling, extend the opposite arm and leg while keeping the trunk still.',
                rationale: 'Trunk stabilisation with low compressive load on the spine.'
            }
        ]
    },
    {
        match: /\b(knee|oa knee|osteoarthritis|patellofemoral|acl|meniscus|ركبة)\b/i,
        exercises: [
            {
                name: 'Quadriceps Setting',
                nameAr: 'شد عضلة الفخذ الرباعية',
                sets: '3 sets',
                reps: '10 reps',
                duration: 'Hold 5s',
                instructions: 'Sitting with the leg straight, tighten the thigh muscle and press the back of the knee down.',
                rationale: 'Early quadriceps activation without joint loading; addresses arthrogenic inhibition.'
            },
            {
                name: 'Straight Leg Raise',
                nameAr: 'رفع الساق المستقيمة',
                sets: '3 sets',
                reps: '10 reps',
                duration: 'Hold 3s at top',
                instructions: 'Supine, keep the knee locked and lift the leg to 30–45°, then lower slowly.',
                rationale: 'Strengthens quadriceps and hip flexors with minimal patellofemoral compression.'
            },
            {
                name: 'Terminal Knee Extension',
                nameAr: 'البسط النهائي للركبة',
                sets: '3 sets',
                reps: '12 reps',
                duration: '—',
                instructions: 'Standing with a resistance band behind the knee, extend the knee fully against the band.',
                rationale: 'Closed-chain quadriceps loading through the final 30° of extension.'
            },
            {
                name: 'Clams Exercise',
                nameAr: 'تمرين المحار',
                sets: '3 sets',
                reps: '10 reps',
                duration: '—',
                instructions: 'Side-lying with hips and knees bent, lift the top knee while keeping the feet together and pelvis still.',
                rationale: 'Gluteus medius strengthening to correct dynamic valgus at the knee.'
            }
        ]
    },
    {
        match: /\b(shoulder|frozen|adhesive capsulitis|rotator cuff|impingement|كتف)\b/i,
        exercises: [
            {
                name: 'Pendulum Exercise',
                nameAr: 'تمرين البندول',
                sets: '3 sets',
                reps: '10 circles each way',
                duration: '—',
                instructions: 'Lean forward supported by the unaffected arm and let the affected arm swing in small circles.',
                rationale: 'Grade I–II oscillatory mobilisation; pain relief in the acute/freezing stage.'
            },
            {
                name: 'Wall Walk / Finger Ladder',
                nameAr: 'تسلق الحائط بالأصابع',
                sets: '3 sets',
                reps: '8 reps',
                duration: 'Hold 10s at end range',
                instructions: 'Facing a wall, walk the fingers upward to progressively increase shoulder flexion.',
                rationale: 'Graded active-assisted range of motion into flexion.'
            },
            {
                name: 'External Rotation with Band',
                nameAr: 'الدوران الخارجي بالمطاط',
                sets: '3 sets',
                reps: '12 reps',
                duration: '—',
                instructions: 'Elbow tucked at 90°, rotate the forearm outward against a resistance band.',
                rationale: 'Rotator cuff strengthening in a low-irritability position.'
            }
        ]
    },
    {
        match: /\b(cervical|neck|whiplash|رقبة|عنق)\b/i,
        exercises: [
            {
                name: 'Chin Tuck',
                nameAr: 'سحب الذقن',
                sets: '3 sets',
                reps: '10 reps',
                duration: 'Hold 5s',
                instructions: 'Draw the chin straight back to lengthen the back of the neck, without tilting the head.',
                rationale: 'Deep neck flexor activation; core of cervicogenic pain management.'
            },
            {
                name: 'Scapular Retraction',
                nameAr: 'سحب لوح الكتف',
                sets: '3 sets',
                reps: '12 reps',
                duration: 'Hold 5s',
                instructions: 'Squeeze the shoulder blades together and down, keeping the shoulders relaxed.',
                rationale: 'Addresses the scapular component of upper-crossed postural syndrome.'
            },
            {
                name: 'Upper Trapezius Stretch',
                nameAr: 'إطالة العضلة شبه المنحرفة العلوية',
                sets: '2 sets',
                reps: '3 reps each side',
                duration: 'Hold 30s',
                instructions: 'Tilt the ear toward the shoulder with gentle overpressure from the same-side hand.',
                rationale: 'Reduces tone in a commonly overactive muscle in neck pain.'
            }
        ]
    },
    {
        match: /\b(stroke|cva|hemiplegia|hemiparesis|جلطة|شلل)\b/i,
        exercises: [
            {
                name: 'Bridging',
                nameAr: 'تمرين الجسر',
                sets: '3 sets',
                reps: '10 reps',
                duration: 'Hold 5s',
                instructions: 'Supine with knees bent, lift the pelvis off the bed keeping weight even through both feet.',
                rationale: 'Trunk and hip extensor activation; prerequisite for bed mobility and transfers.'
            },
            {
                name: 'Sit to Stand Practice',
                nameAr: 'الوقوف من الجلوس',
                sets: '3 sets',
                reps: '8 reps',
                duration: '—',
                instructions: 'Rise from a chair with feet behind the knees and weight shifted forward. Progress by lowering the seat height.',
                rationale: 'Task-specific training; strongest evidence base for functional recovery post-stroke.'
            },
            {
                name: 'Weight Shift in Standing',
                nameAr: 'نقل الوزن في الوقوف',
                sets: '3 sets',
                reps: '10 reps each side',
                duration: 'Hold 3s',
                instructions: 'In supported standing, shift body weight onto the affected limb and back.',
                rationale: 'Improves affected-side loading and standing balance symmetry.'
            }
        ]
    }
];

const GENERIC: Omit<SuggestedExercise, 'origin'>[] = [
    {
        name: 'Active Range of Motion',
        nameAr: 'المدى الحركي النشط',
        sets: '3 sets',
        reps: '10 reps',
        duration: '—',
        instructions: 'Move the affected joint actively through the pain-free range in all available directions.',
        rationale: 'Maintains joint mobility and reduces stiffness during the early phase.'
    },
    {
        name: 'Isometric Strengthening',
        nameAr: 'التقوية الثابتة',
        sets: '3 sets',
        reps: '8 reps',
        duration: 'Hold 10s',
        instructions: 'Contract the target muscle against an immovable resistance without changing joint angle.',
        rationale: 'Builds strength without joint movement; tolerated in irritable presentations.'
    },
    {
        name: 'Graded Aerobic Activity',
        nameAr: 'النشاط الهوائي المتدرج',
        sets: 'Daily',
        reps: '—',
        duration: '15–30 min',
        instructions: 'Walking or stationary cycling at a conversational pace, progressing duration weekly.',
        rationale: 'General conditioning and central pain modulation.'
    }
];

function fromLibrary(diagnosis: string): SuggestedExercise[] {
    const protocol = PROTOCOLS.find((p) => p.match.test(diagnosis));
    const list = protocol ? protocol.exercises : GENERIC;
    return list.map((e) => ({ ...e, origin: 'library' as const }));
}

const EXERCISE_SCHEMA = {
    type: 'object',
    properties: {
        exercises: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    name: { type: 'string' },
                    nameAr: { type: 'string' },
                    sets: { type: 'string' },
                    reps: { type: 'string' },
                    duration: { type: 'string' },
                    instructions: { type: 'string' },
                    rationale: { type: 'string' }
                },
                required: ['name', 'nameAr', 'sets', 'reps', 'duration', 'instructions', 'rationale'],
                additionalProperties: false
            }
        }
    },
    required: ['exercises'],
    additionalProperties: false
} as const;

/**
 * Suggests exercises for a diagnosis. Uses Claude when ANTHROPIC_API_KEY is set,
 * grounding the suggestions in the supplied abstracts; otherwise returns the
 * matching built-in protocol.
 */
export async function suggestExercises(
    diagnosis: string,
    papers: Paper[],
    context?: { age?: number | null; contraindications?: string; medicalHistory?: string }
): Promise<{ exercises: SuggestedExercise[]; usedAi: boolean; note?: string }> {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
        return {
            exercises: fromLibrary(diagnosis),
            usedAi: false,
            note: 'Set ANTHROPIC_API_KEY to generate patient-specific suggestions. Showing the built-in protocol.'
        };
    }

    const evidence = papers
        .slice(0, 5)
        .map((p, i) => `[${i + 1}] ${p.title} (${p.year ?? 'n.d.'}, ${p.venue}). ${p.abstract.slice(0, 900)}`)
        .join('\n\n');

    const patient = [
        context?.age ? `Age: ${context.age}` : '',
        context?.contraindications ? `Contraindications / precautions: ${context.contraindications}` : '',
        context?.medicalHistory ? `Medical history: ${context.medicalHistory}` : ''
    ]
        .filter(Boolean)
        .join('\n');

    try {
        const client = new Anthropic({ apiKey });
        const response = await client.messages.create({
            model: 'claude-opus-5',
            max_tokens: 16000,
            system: [
                'You are assisting a licensed physiotherapist who is building a treatment program.',
                'Propose 4-6 exercises appropriate for the diagnosis, grounded in the supplied abstracts where they are relevant.',
                'Respect any stated contraindications — never propose a movement they rule out.',
                'Write instructions a patient can follow, and keep each rationale to one clinical sentence.',
                'Provide nameAr as the Arabic name of the exercise.',
                'These are suggestions for a clinician to review, not a prescription.'
            ].join(' '),
            output_config: { format: { type: 'json_schema', schema: EXERCISE_SCHEMA } },
            messages: [
                {
                    role: 'user',
                    content: `Diagnosis: ${diagnosis}\n${patient}\n\nEvidence:\n${evidence || '(no abstracts retrieved)'}`
                }
            ]
        });

        if (response.stop_reason === 'refusal') {
            return { exercises: fromLibrary(diagnosis), usedAi: false, note: 'Model declined; showing the built-in protocol.' };
        }

        const text = response.content.find((b) => b.type === 'text');
        if (!text || text.type !== 'text') throw new Error('empty response');

        const parsed = JSON.parse(text.text) as { exercises: Omit<SuggestedExercise, 'origin'>[] };
        return {
            exercises: parsed.exercises.map((e) => ({ ...e, origin: 'ai' as const })),
            usedAi: true
        };
    } catch (error) {
        return {
            exercises: fromLibrary(diagnosis),
            usedAi: false,
            note: `AI suggestion unavailable (${error instanceof Error ? error.message : 'unknown error'}). Showing the built-in protocol.`
        };
    }
}
