/**
 * مكتبة التمارين الأولية للمركز.
 *
 * النصوص العربية والإنجليزية مكتوبة إكلينيكيًا: لكل تمرين ملخص فائدته، وخطوات التنفيذ
 * كما تُقرأ للمريض، وتحذير السلامة الذي يمنع الخطأ الشائع. الوسائط فارغة عمدًا —
 * يرفع المركز فيديوهاته الخاصة من شاشة التمارين.
 */
import type { BodyRegion, Exercise, ExerciseLevel } from './types';
import { uid } from './storage';

/** يختصر تعريف السجل حتى تبقى المكتبة مقروءة كمحتوى لا ككود */
function x(
    name: string,
    nameEn: string,
    summary: string,
    summaryEn: string,
    region: BodyRegion,
    equipment: string,
    equipmentEn: string,
    level: ExerciseLevel,
    instructions: string,
    instructionsEn: string,
    cautions: string,
    cautionsEn: string,
    defaultSets: number,
    defaultReps: number,
    defaultHold: number,
    tags: string[]
): Exercise {
    return {
        id: uid('x_'),
        name,
        nameEn,
        summary,
        summaryEn,
        region,
        equipment,
        equipmentEn,
        level,
        instructions,
        instructionsEn,
        cautions,
        cautionsEn,
        videoUrl: '',
        imageUrl: '',
        defaultSets,
        defaultReps,
        defaultHold,
        defaultPerDay: 1,
        tags,
        active: true,
        createdAt: new Date().toISOString()
    };
}

export function starterExercises(): Exercise[] {
    return [
        x(
            'أبجدية الكاحل',
            'Ankle alphabet',
            'يعيد مدى حركة الكاحل في كل الاتجاهات بعد الالتواء أو رفع الجبس.',
            'Restores ankle movement in every direction after a sprain or once a cast comes off.',
            'ankle',
            'بدون',
            'None',
            'easy',
            'اجلس على كرسي وارفع قدمك المصابة قليلًا عن الأرض.\n\nتخيل أنك تكتب حروف الأبجدية في الهواء بإبهام قدمك، من الألف إلى الياء.\n\nالحركة كلها من الكاحل — ساقك تبقى ثابتة تمامًا.\n\nهذا التمرين يحرك الكاحل في كل الاتجاهات بلا حاجة لتذكر تمارين منفصلة، وهو مثالي في الأيام الأولى بعد الالتواء أو بعد رفع الجبس.',
            'Sit on a chair and lift the affected foot slightly off the floor.\n\nImagine writing the letters of the alphabet in the air with your big toe, from A to Z.\n\nAll the movement comes from the ankle — your leg stays completely still.\n\nThis moves the ankle through every direction without having to remember separate exercises, and it is ideal in the first days after a sprain or once a cast is removed.',
            'الحركة من الكاحل فقط — ثبّت ساقك ولا تحركها.',
            'Move the ankle only — keep your leg still.',
            2,
            1,
            0,
            ['مرحلة مبكرة', 'ما بعد الجراحة', 'مدى حركة']
        ),
        x(
            'إمالة الحوض',
            'Pelvic tilt',
            'ينشط عضلات البطن العميقة ويخفف الضغط على أسفل الظهر.',
            'Activates the deep abdominal muscles and unloads the low back.',
            'back',
            'حصيرة',
            'Mat',
            'easy',
            'استلقِ على ظهرك والركبتان مثنيتان والقدمان على الأرض.\n\nشد عضلات بطنك برفق واضغط أسفل ظهرك ناحية الأرض حتى تختفي المسافة تحته.\n\nاثبت خمس ثوانٍ مع التنفس الطبيعي — لا تحبس نفسك — ثم استرخِ.\n\nالحركة صغيرة جدًا؛ لو ارتفعت أردافك عن الأرض فأنت تبالغ فيها.',
            'Lie on your back with knees bent and feet flat on the floor.\n\nGently tighten your abdominal muscles and press your low back down towards the floor until the gap beneath it closes.\n\nHold for five seconds while breathing normally — do not hold your breath — then relax.\n\nThe movement is very small; if your buttocks lift off the floor, you are overdoing it.',
            'حركة صغيرة — لا ترفع الأرداف عن الأرض.',
            'A small movement — do not lift your buttocks off the floor.',
            3,
            12,
            5,
            ['مرحلة مبكرة']
        ),
        x(
            'تمرين القط والبقرة',
            'Cat–cow',
            'يحرك فقرات الظهر في المدى الكامل ويخفف التيبس الصباحي.',
            'Moves the spine through its full range and eases morning stiffness.',
            'back',
            'حصيرة',
            'Mat',
            'easy',
            'ابدأ على أربع: اليدان تحت الكتفين والركبتان تحت الوركين.\n\nمع الشهيق: أنزل بطنك لأسفل وارفع رأسك وعظمة العصعص لأعلى فيتقوس ظهرك للداخل.\n\nمع الزفير: قوّس ظهرك لأعلى نحو السقف وأنزل رأسك بين ذراعيك.\n\nتحرك ببطء بين الوضعين مع التنفس. هذا تمرين ممتاز لبدء اليوم إن كنت تستيقظ بظهر متيبس.',
            'Start on all fours: hands under shoulders, knees under hips.\n\nAs you breathe in: let your belly drop, lift your head and tailbone so your back arches downwards.\n\nAs you breathe out: round your back up towards the ceiling and drop your head between your arms.\n\nMove slowly between the two positions with your breath. This is an excellent way to start the day if you wake with a stiff back.',
            'تحرك في المدى المريح فقط ولا تصل لحد الألم.',
            'Move only within a comfortable range — never into pain.',
            2,
            10,
            0,
            ['مرحلة مبكرة', 'مدى حركة']
        ),
        x(
            'تمرين الطائر والكلب',
            'Bird dog',
            'يبني ثبات الجذع دون تحميل العمود الفقري — أساسي في علاج آلام الظهر.',
            'Builds trunk stability without loading the spine — a mainstay of back pain treatment.',
            'back',
            'حصيرة',
            'Mat',
            'medium',
            'ابدأ على أربع: اليدان تحت الكتفين والركبتان تحت الوركين، والظهر مستقيم.\n\nمُد ذراعك اليمنى للأمام وساقك اليسرى للخلف في نفس الوقت حتى يصيرا في مستوى ظهرك.\n\nالمهم أن يبقى حوضك ثابتًا تمامًا بلا ميل لأي جانب — تخيل كوب ماء موضوعًا على أسفل ظهرك لا يجب أن ينسكب.\n\nاثبت خمس ثوانٍ، ارجع ببطء، ثم بدّل الجهة.',
            'Start on all fours: hands under shoulders, knees under hips, back flat.\n\nExtend your right arm forwards and your left leg backwards at the same time, until both are level with your back.\n\nWhat matters is that your pelvis stays completely still, without tipping to either side — imagine a glass of water resting on your low back that must not spill.\n\nHold five seconds, return slowly, then swap sides.',
            'لا تدع حوضك يميل؛ الثبات أهم من ارتفاع الطرف.',
            'Do not let your pelvis tip; stability matters more than how high the limb goes.',
            3,
            8,
            5,
            ['ثبات']
        ),
        x(
            'جسر الأرداف',
            'Glute bridge',
            'يقوي عضلات الأرداف التي تحمي أسفل الظهر والركبة معًا.',
            'Strengthens the gluteal muscles that protect both the low back and the knee.',
            'hip',
            'حصيرة',
            'Mat',
            'medium',
            'استلقِ على ظهرك والركبتان مثنيتان والقدمان على الأرض بعرض الحوض.\n\nشد عضلات أردافك أولًا، ثم ارفع حوضك عن الأرض حتى يصير جسمك خطًا مستقيمًا من الكتف إلى الركبة.\n\nاثبت ثلاث ثوانٍ مع استمرار شد الأرداف، ثم أنزل فقرة فقرة ببطء.\n\nضعف عضلات الأرداف سبب شائع لآلام أسفل الظهر وآلام الركبة معًا، فهذا التمرين يفيد الاثنين.',
            'Lie on your back with knees bent and feet flat, hip-width apart.\n\nSqueeze your buttocks first, then lift your hips off the floor until your body forms a straight line from shoulder to knee.\n\nHold three seconds while keeping the squeeze, then lower slowly, one vertebra at a time.\n\nWeak glutes are a common cause of both low back pain and knee pain, so this exercise helps both.',
            'لو شعرت بشد في خلفية الفخذ بدل الأرداف، قرّب قدميك من أردافك.',
            'If you feel it in the back of your thigh instead of the buttocks, bring your feet closer to you.',
            3,
            12,
            3,
            ['تقوية']
        ),
        x(
            'شد العضلة الرباعية',
            'Quadriceps sets',
            'ينشط العضلة الأمامية للفخذ بلا تحريك الركبة — أول تمرين بعد جراحة الركبة.',
            'Activates the front thigh muscle without moving the knee — the first exercise after knee surgery.',
            'knee',
            'منشفة',
            'Towel',
            'easy',
            'استلقِ أو اجلس والساق ممدودة أمامك.\n\nضع منشفة مطوية تحت الركبة.\n\nاضغط بمؤخرة ركبتك على المنشفة مع شد عضلة الفخذ الأمامية، فترتفع الرضفة قليلًا لأعلى.\n\nاثبت خمس ثوانٍ ثم استرخِ. هذا التمرين لا يحرك المفصل، لذا يُسمح به مبكرًا جدًا، وهو أساسي لمنع ضمور العضلة بعد الجراحة أو الجبس.',
            'Lie or sit with your leg straight out in front of you.\n\nPlace a folded towel under your knee.\n\nPress the back of your knee down into the towel while tightening the front thigh muscle, so the kneecap draws slightly upwards.\n\nHold five seconds, then relax. This exercise does not move the joint, so it is permitted very early, and it is essential for preventing muscle wasting after surgery or a cast.',
            'آمن حتى في الأيام الأولى بعد الجراحة ما لم يمنعك جراحك.',
            'Safe even in the first days after surgery unless your surgeon says otherwise.',
            3,
            15,
            5,
            ['مرحلة مبكرة', 'ما بعد الجراحة']
        ),
        x(
            'رفع الساق المستقيمة',
            'Straight leg raise',
            'يقوي العضلة الرباعية بتحميل أكبر مع بقاء الركبة ثابتة.',
            'Strengthens the quadriceps under greater load while the knee stays locked.',
            'knee',
            'بدون',
            'None',
            'medium',
            'استلقِ على ظهرك، واثنِ الساق السليمة والقدم على الأرض، وأبقِ الساق المصابة ممدودة.\n\nشد عضلة الفخذ الأمامية أولًا حتى تُقفل الركبة تمامًا.\n\nارفع الساق المستقيمة نحو ثلاثين سنتيمترًا عن الأرض مع بقاء الركبة مفرودة تمامًا.\n\nاثبت ثلاث ثوانٍ ثم أنزل ببطء — النزول البطيء هو الجزء الذي يبني القوة فعلًا.',
            'Lie on your back, bend your good leg with the foot flat, and keep the affected leg straight.\n\nFirst tighten the front thigh muscle so the knee locks out completely.\n\nRaise the straight leg about thirty centimetres from the floor, keeping the knee fully straight.\n\nHold three seconds, then lower slowly — the slow lowering is the part that actually builds strength.',
            'لو انثنت ركبتك أثناء الرفع فالعضلة لم تقوَ بعد — ارجع لتمرين شد العضلة الرباعية.',
            'If your knee bends as you lift, the muscle is not ready — go back to quad sets.',
            3,
            12,
            3,
            ['تقوية']
        ),
        x(
            'سحب الذقن',
            'Chin tuck',
            'يصحح وضع الرأس الأمامي ويقوي عضلات الرقبة العميقة.',
            'Corrects forward head posture and strengthens the deep neck flexors.',
            'neck',
            'بدون',
            'None',
            'easy',
            'اجلس أو قف مستقيم الظهر والكتفان مسترخيتان.\n\nاسحب ذقنك للخلف في خط أفقي كأنك تصنع «ذقنًا مزدوجًا» — بلا إمالة الرأس لأعلى أو لأسفل.\n\nستشعر بشد خفيف في مؤخرة الرقبة. اثبت خمس ثوانٍ ثم استرخِ.\n\nهذا من أنفع التمارين لمن يجلس أمام شاشة طويلًا. كرره كل ساعة أثناء العمل.',
            'Sit or stand with a straight back and relaxed shoulders.\n\nDraw your chin straight back in a horizontal line, as if making a "double chin" — without tipping your head up or down.\n\nYou should feel a gentle stretch at the back of the neck. Hold for five seconds, then release.\n\nThis is one of the most useful exercises for anyone at a screen all day. Repeat it every hour while working.',
            'توقف إن سبب دوخة أو تنميل في الذراع.',
            'Stop if it causes dizziness or arm numbness.',
            3,
            10,
            5,
            ['مرحلة مبكرة', 'تقوية']
        ),
        x(
            'إطالة جانب الرقبة',
            'Neck side stretch',
            'يطيل العضلة شبه المنحرفة العلوية ويخفف التوتر بين الرقبة والكتف.',
            'Lengthens the upper trapezius and eases tension between neck and shoulder.',
            'neck',
            'بدون',
            'None',
            'easy',
            'اجلس مستقيمًا وثبّت يدك اليمنى تحت المقعد أو بجانبك لتثبيت الكتف.\n\nأمِل رأسك برفق ناحية الكتف الأيسر حتى تشعر بشد على الجانب الأيمن من الرقبة.\n\nيمكنك وضع يدك اليسرى فوق رأسك لزيادة الإطالة قليلًا — بثقل اليد فقط بلا جذب.\n\nاثبت عشرين إلى ثلاثين ثانية، ثم بدّل الجانب.',
            'Sit tall and anchor your right hand under the seat or by your side to hold the shoulder down.\n\nGently tilt your head towards your left shoulder until you feel a stretch on the right side of the neck.\n\nYou may rest your left hand on your head to add a little more stretch — using the weight of the hand only, with no pulling.\n\nHold twenty to thirty seconds, then swap sides.',
            'إطالة لطيفة فقط — لا تجذب رأسك بقوة.',
            'Gentle stretch only — never pull hard on your head.',
            2,
            3,
            20,
            ['مرحلة مبكرة', 'إطالة']
        ),
        x(
            'التمرين البندولي',
            'Pendulum exercise',
            'أول تمرين بعد إصابة أو جراحة الكتف: يحرك المفصل بلا إجهاد للعضلات.',
            'The first exercise after a shoulder injury or operation: it moves the joint without working the muscles.',
            'shoulder',
            'بدون',
            'None',
            'easy',
            'قف وانحنِ للأمام قليلًا، واستند بيدك السليمة على طاولة أو ظهر كرسي.\n\nاترك الذراع المصابة متدلية تمامًا ومسترخية.\n\nحرّك جسمك — لا كتفك — في دوائر صغيرة، فتتبع الذراع الحركة بثقلها وحدها. عشر دورات في كل اتجاه.\n\nكرر الحركة أمامًا وخلفًا، ثم يمينًا ويسارًا. هذا التمرين آمن جدًا في المراحل المبكرة لأنه لا يتطلب انقباض عضلات الكتف.',
            'Stand and lean forwards slightly, supporting yourself on a table or chair back with your good hand.\n\nLet the injured arm hang down, completely relaxed.\n\nMove your body — not your shoulder — in small circles, so the arm follows under its own weight. Ten circles in each direction.\n\nRepeat forwards and backwards, then side to side. This is very safe in the early stages because it requires no shoulder muscle contraction.',
            'الذراع مسترخية تمامًا — الحركة من الجسم لا من الكتف.',
            'The arm must hang completely relaxed — the movement comes from your body, not your shoulder.',
            3,
            10,
            0,
            ['مرحلة مبكرة', 'مدى حركة']
        ),
        x(
            'انزلاق الذراع على الحائط',
            'Wall slide',
            'يستعيد رفع الكتف تدريجيًا بمساعدة الحائط لتقليل الحمل.',
            'Gradually restores shoulder elevation, with the wall taking part of the load.',
            'shoulder',
            'حائط',
            'Wall',
            'medium',
            'قف مواجهًا الحائط على بعد قدم منه تقريبًا.\n\nضع يدك على الحائط عند مستوى الخصر، ثم أزلقها لأعلى ببطء وكأنك تمسح الحائط.\n\nالحائط يحمل جزءًا من ثقل الذراع، فيصبح الرفع أسهل مما لو رفعتها في الهواء.\n\nتوقف عند أول حد يبدأ فيه الألم، اثبت لحظة، ثم أنزل ببطء. مع الأيام ستلاحظ أن يدك تصل أعلى.',
            "Stand facing a wall, about a foot away from it.\n\nPlace your hand on the wall at waist height, then slide it slowly upwards as though wiping the wall.\n\nThe wall carries part of the arm's weight, so lifting is easier than raising it in the air.\n\nStop at the first point where pain begins, pause a moment, then lower slowly. Over the days you will notice your hand reaching higher.",
            'ارتفع بقدر ما يسمح الألم — لا تجبر المفصل.',
            'Go only as high as pain allows — never force the joint.',
            3,
            10,
            0,
            []
        ),
        x(
            'الدوران الخارجي للكتف',
            'Shoulder external rotation',
            'يقوي عضلات الكفة المدورة التي تثبّت مفصل الكتف.',
            'Strengthens the rotator cuff muscles that stabilise the shoulder joint.',
            'shoulder',
            'شريط مطاطي',
            'Resistance band',
            'medium',
            'ثبّت شريطًا مطاطيًا في مستوى الخصر واقبض طرفه باليد المصابة.\n\nقف بحيث يكون الكوع ملاصقًا لجنبك ومثنيًا بزاوية تسعين درجة، والساعد أمام بطنك.\n\nأدر ساعدك للخارج مبتعدًا عن جسمك مع إبقاء الكوع في مكانه تمامًا — ضع منشفة مطوية تحت الكوع لتساعدك على تثبيته.\n\nارجع ببطء. الحركة قصيرة لكنها من أهم تمارين استقرار الكتف.',
            'Anchor a resistance band at waist height and hold the end in your affected hand.\n\nStand with your elbow tucked against your side and bent to ninety degrees, forearm across your stomach.\n\nRotate your forearm outwards, away from your body, keeping the elbow exactly where it is — tuck a folded towel under the elbow to help hold it in place.\n\nReturn slowly. The movement is small but it is one of the most important shoulder stability exercises.',
            'أبقِ الكوع ملاصقًا لجنبك — الحركة من الكتف لا من الجذع.',
            'Keep your elbow tucked to your side — the movement comes from the shoulder, not the trunk.',
            3,
            12,
            0,
            ['تقوية']
        ),
        /* ــــ تمارين تكمل التغطية: الجذع والاتزان وربلة الساق ومدى حركة الركبة ــــ */
        x(
            'البلانك على الكوعين',
            'Forearm plank',
            'يبني ثبات الجذع كله في وضع واحد بلا حركة تحمّل الظهر.',
            'Builds whole-trunk stability in one static position that spares the spine.',
            'core',
            'حصيرة',
            'Mat',
            'medium',
            'استند على كوعيك وأطراف قدميك، والكوعان تحت الكتفين تمامًا.\n\nشدّ عضلات بطنك وأردافك معًا حتى يصير جسمك خطًا مستقيمًا من الكعب إلى الرأس.\n\nتنفّس بطبيعية أثناء الثبات — لا تحبس نفسك.\n\nابدأ بعشرين ثانية وزد خمس ثوانٍ كل أسبوع. الثبات الصحيح لعشرين ثانية أنفع من دقيقة بحوض هابط.',
            'Rest on your forearms and toes, elbows directly under your shoulders.\n\nTighten your abdominals and buttocks together until your body forms a straight line from heel to head.\n\nBreathe normally while you hold — do not hold your breath.\n\nStart at twenty seconds and add five seconds each week. Twenty seconds in good form beats a minute with a sagging hip.',
            'لو هبط حوضك أو آلمك ظهرك فتوقف — المدة الأقصر بوضع سليم أفضل.',
            'Stop if your hips drop or your back hurts — a shorter hold in good form is better.',
            3,
            1,
            20,
            ['ثبات', 'تقوية']
        ),
        x(
            'ثني الركبة على الكرسي',
            'Seated knee flexion',
            'يستعيد ثني الركبة تدريجيًا بعد الجراحة أو رفع الجبس.',
            'Gradually restores knee bending after surgery or once a cast is removed.',
            'knee',
            'كرسي',
            'Chair',
            'easy',
            'اجلس على كرسي ثابت والقدمان على الأرض.\n\nحرّك القدم المصابة للخلف تحت الكرسي ببطء حتى تشعر بشدّ في مقدمة الركبة.\n\nيمكنك الاستعانة بالقدم السليمة خلف الكعب لدفع لطيف يزيد الثني قليلًا.\n\nاثبت ثماني ثوانٍ ثم عد. قِس تقدمك أسبوعيًا: المسافة التي تصلها القدم للخلف تزيد تدريجيًا.',
            'Sit on a stable chair with both feet on the floor.\n\nSlide the affected foot back under the chair slowly until you feel a stretch at the front of the knee.\n\nYou may use the good foot behind the heel to give a gentle push for a little more bend.\n\nHold eight seconds, then return. Track your progress weekly: the distance the foot slides back should grow.',
            'شدّ مقبول، ألم حاد لا. لا تدفع بقوة بعد الجراحة إلا بإذن جراحك.',
            "A stretch is fine, sharp pain is not. After surgery do not force it without your surgeon's approval.",
            3,
            10,
            8,
            ['مدى حركة', 'ما بعد الجراحة']
        ),
        x(
            'إطالة أوتار الركبة الخلفية',
            'Hamstring stretch',
            'يطيل خلفية الفخذ التي يسبب قِصَرها شدًّا على أسفل الظهر.',
            'Lengthens the back of the thigh, whose tightness pulls on the low back.',
            'hip',
            'منشفة',
            'Towel',
            'easy',
            'استلقِ على ظهرك واثنِ الساق السليمة والقدم على الأرض.\n\nلُفّ منشفة حول مشط القدم المصابة وارفع الساق مستقيمة نحو السقف.\n\nاسحب المنشفة برفق حتى تشعر بشدّ خلف الفخذ — لا في الركبة.\n\nاثبت ثلاثين ثانية بتنفس طبيعي. الإطالة تحتاج وقتًا لا قوة: ثلاثون ثانية هادئة أنفع من عشر ثوانٍ بجذب عنيف.',
            'Lie on your back, bend the good leg and keep that foot on the floor.\n\nLoop a towel around the ball of the affected foot and raise the leg straight towards the ceiling.\n\nPull gently on the towel until you feel a stretch behind the thigh — not in the knee.\n\nHold thirty seconds, breathing normally. Stretching needs time, not force: a calm thirty seconds beats ten seconds of hard pulling.',
            'أبقِ الركبة مفرودة والظهر ملاصقًا للأرض. توقف لو جاءك تنميل في الساق.',
            'Keep the knee straight and your back flat on the floor. Stop if you get any tingling down the leg.',
            2,
            3,
            30,
            ['إطالة', 'مرحلة مبكرة']
        ),
        x(
            'الوقوف على قدم واحدة',
            'Single-leg stance',
            'يدرّب الاتزان الذي يقي كبار السن من السقوط ويعيد ثقة الكاحل بعد الالتواء.',
            'Trains the balance that protects older patients from falls and rebuilds ankle confidence after a sprain.',
            'balance',
            'كرسي للأمان',
            'Chair for safety',
            'medium',
            'قف بجوار حائط أو ظهر كرسي تستطيع الإمساك به فورًا عند الحاجة.\n\nارفع قدمًا واحدة قليلًا عن الأرض وحافظ على اتزانك ثلاثين ثانية.\n\nابدأ ويدك على الكرسي، ثم بإصبع واحدة، ثم بلا مساعدة، ثم — إن أمنت تمامًا — بعينين مغلقتين.\n\nبدّل القدمين. تحسّن الاتزان يظهر في أسابيع لا أيام، فداوم عليه.',
            'Stand beside a wall or a chair back you can grab immediately if needed.\n\nLift one foot slightly off the floor and keep your balance for thirty seconds.\n\nStart with your hand on the chair, then one finger, then no support, then — only when fully safe — with your eyes closed.\n\nSwap feet. Balance improves over weeks, not days, so keep at it.',
            'لا تجرب هذا التمرين وحدك إن كنت تسقط بسهولة — اطلب من أحد أن يرافقك.',
            'Do not try this alone if you fall easily — have someone stay with you.',
            3,
            1,
            30,
            ['اتزان', 'كبار السن']
        ),
        x(
            'رفع الكعبين',
            'Heel raises',
            'يقوي ربلة الساق التي تدفع الجسم في كل خطوة وتحمي وتر أخيل.',
            'Strengthens the calf that pushes you forward with every step and protects the Achilles tendon.',
            'ankle',
            'حائط للاتزان',
            'Wall for balance',
            'easy',
            'قف مستقيمًا والقدمان بعرض الحوض، ويداك على الحائط للاتزان لا للحمل.\n\nارفع كعبيك عن الأرض ببطء حتى تقف على مشط قدميك.\n\nاثبت لحظة في الأعلى ثم انزل ببطء شديد — النزول البطيء هو ما يبني القوة فعلًا.\n\nلو صار التمرين سهلًا، نفّذه على قدم واحدة.',
            'Stand upright with feet hip-width apart, hands on the wall for balance, not for support.\n\nSlowly lift your heels off the floor until you are on the balls of your feet.\n\nPause briefly at the top, then lower very slowly — the slow lowering is what actually builds strength.\n\nOnce it feels easy, do it on one leg.',
            'انزل ببطء. النزول السريع يفقدك أهم جزء في التمرين.',
            'Lower slowly. Dropping quickly wastes the most useful part of the exercise.',
            3,
            15,
            2,
            ['تقوية', 'مرحلة مبكرة']
        )
    ]; // مكان التمارين الإضافية
}
